# Generated by Django 3.0.6 on 2020-05-25 06:40

from django.db import migrations


def _method(apps, schema_editor):
    # Crear roles principales del sistema.
    rol = apps.get_model('all', 'Rol')
    administrador = rol.objects.create(nombre='Administrador')
    cliente = rol.objects.create(nombre='Cliente')


class Migration(migrations.Migration):

    dependencies = [
        ('all', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(_method, reverse_code=migrations.RunPython.noop)
    ]
